// Open Lounge Phone project site. Content in src/content/docs/ is generated by
// scripts/sync-docs.ts from the main repository (main/ submodule) — edit the sources there.
import starlight from "@astrojs/starlight";
import { defineConfig } from "astro/config";

export default defineConfig({
  site: "https://openloungephone.app",
  outDir: "./dist",
  integrations: [
    starlight({
      title: "Open Lounge Phone",
      description: "A screen-light phone for kids and lounges — open source, self-hosted, no spam.",
      logo: { src: "./src/logo.svg" },
      favicon: "/favicon.svg",
      customCss: ["./src/styles/theme.css"],
      // Footer: the project credit and Sponsor link. Header: GitHub icon and a Donate button.
      components: {
        Footer: "./src/components/Footer.astro",
        SocialIcons: "./src/components/SocialIcons.astro",
      },
      social: [
        { icon: "github", label: "GitHub", href: "https://github.com/Open-Lounge-Phone/open-lounge-phone" },
      ],
      lastUpdated: false,
      pagination: true,
      sidebar: [
        {
          label: "Start here",
          items: [
            { label: "Introduction", slug: "intro" },
            { label: "Getting started", slug: "getting-started" },
          ],
        },
        { label: "How-to", items: [{ autogenerate: { directory: "how-to" } }] },
        { label: "Reference", items: [{ autogenerate: { directory: "reference" } }] },
        { label: "Hardware", items: [{ autogenerate: { directory: "hardware" } }] },
        { label: "Project", items: [{ autogenerate: { directory: "project" } }] },
      ],
    }),
  ],
});
